# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 10:07
from __future__ import unicode_literals

import jsonfield.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payu_order_id', models.CharField(max_length=255, verbose_name='PayU order ID')),
                ('pos_id', models.CharField(max_length=255, verbose_name='PayU POS ID')),
                ('customer_ip', models.CharField(max_length=255, verbose_name='customer IP')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('PENDING', 'Pending'), ('WAITING_FOR_CONFIRMATION', 'Waiting for confirmation'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled'), ('REJECTED', 'Rejected')], default='NEW', max_length=255, verbose_name='status')),
                ('total', models.PositiveIntegerField(verbose_name='total')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('products', jsonfield.fields.JSONField(blank=True, default='', verbose_name='products')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name_plural': 'payments',
                'verbose_name': 'payment',
            },
        ),
    ]
