# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created',), 'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
